const images = {
    phone: require('../assets/images/printpass.jpg'),
    welcome: require('../assets/images/img1.jpg'),
    role: require('../assets/images/role.jpg'),
    touch: require('../assets/images/img3.jpg'),
    working: require('../assets/images/img2.jpg'),
    login_pic: require('../assets/images/mode-pic.jpg'),
    clock: require('../assets/images/clock.png'),
    calendar: require('../assets/images/calendar.png'),
    fingerprint_scanner: require('../assets/images/biometric.png'),
    error : require('../assets/images/error.jpg'),
    add_session : require('../assets/images/add_session.jpg'),
    register: require('../assets/images/register.jpg'),
    no_session: require('../assets/images/no_session.jpg'),
    not_found: require('../assets/images/not_found.jpg'),
    report: require('../assets/images/report.jpg'),
    clock_icon: require('../assets/images/clock-icon.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    calendar_icon: require('../assets/images/calendar-icon.png'),
    delete: require('../assets/images/delete.png'),
    edit: require('../assets/images/edit.png'),
    add: require('../assets/images/plus.png'),
    close: require('../assets/images/close.png'),
    lock: require('../assets/images/lock.png'),
    user: require('../assets/images/user.png'),
    name: require('../assets/images/name.png'),
    signup: require('../assets/images/signup.jpg'),
    share: require('../assets/images/share.png'),
    pdf: require('../assets/images/pdf.png'),
    excel: require('../assets/images/excel.png'),
    documents: require('../assets/images/documents.png'),
    student: require('../assets/images/student.png'),
  };
  
  export default images;